"""add_user_id_to_quizzes

Revision ID: f80be63155b6
Revises: ef4c5f191201
Create Date: 2025-06-11 12:34:43.049757

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f80be63155b6'
down_revision: Union[str, None] = 'ef4c5f191201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('user_id', sa.BIGINT(), nullable=True))
    op.alter_column('users', 'password',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.LargeBinary(length=60),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.drop_column('quizzes', 'user_id')
    # ### end Alembic commands ###
